/*
 * Medium Problem 2: Makefile or Compilation Script
 * 
 * Take the multi-file library from Medium Problem 1 and write either a 
 * Makefile (Linux/Mac) or a batch script (Windows) that compiles all the 
 * .cpp files and links them into one executable. Add comments explaining 
 * each step.
 * 
 * NOTE: This is a Makefile template. Adjust for your system.
 */

# TODO: Write your Makefile here
# Hint: You'll need rules for compiling .cpp to .o files and linking them

# Example structure:
# all: program
# 
# program: main.o stringutils.o
#     g++ -o program main.o stringutils.o
# 
# main.o: main.cpp stringutils.h
#     g++ -c main.cpp
# 
# stringutils.o: stringutils.cpp stringutils.h
#     g++ -c stringutils.cpp
# 
# clean:
#     rm -f *.o program
